
pipeline:
  test:
    image: python:3.5.2
    environment:
      - DJANGO_SETTINGS_MODULE=init_django.settings.dev
    commands:
      - pip install tox
      - tox


  notify:
    image: drillster/drone-email
    host: mail.ntnu.fap.no
    port: 25
    from: drone@drone.fap.no
    recipients: [ kradalby@kradalby.no ]
    when:
      status: [ success, changed, failure ]


  docker:
    image: plugins/docker
    repo: registry.fap.no/gso/gso
    insecure: true
    tags:
        - latest
    when:
        branch: master

  ssh:
    image: appleboy/drone-ssh
    host:
     - primeape.terra.fap.no
    user: root
    port: 22
    script:
      - docker pull registry.fap.no/gso/gso:latest
      - docker-compose -f /srv/docker/gso/docker-compose.yml stop
      - docker-compose -f /srv/docker/gso/docker-compose.yml up -d
    when:
        status: success
        branch: master
