image: python2.7
script:
    - make env
    - make prod
    - make test
notify:
    email:
        recipients:
            - kradalby@kradalby.no
+deploy:
    ssh:
        target: root@gengar.fap:/srv/www/dfekt.no/gso/ 21337
    artifacts:
        - build.result
    cmd: 
        - touch lol

