pipeline:
  build:
    image: plugins/docker
    repo: kradalby/gso
    # auto_tag: true
    secrets: [ docker_username, docker_password ]
    tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - latest

  deploy:
    image: quay.io/honestbee/drone-kubernetes
    deployment: gso-deployment
    repo: kradalby/gso
    container: gso-container
    namespace: default
    secrets: [ kubernetes_server, kubernetes_cert, kubernetes_token ]
    tag:
        - ${DRONE_COMMIT_SHA:0:8} 

  notify:
    image: drillster/drone-email
    host: mail.ntnu.fap.no
    port: 25
    from: drone@drone.fap.no
    recipients: [ kradalby@kradalby.no ]
    when:
      status: [ success, changed, failure ]
      
