---
{
  "kind": "pipeline",
  "name": "Kubernetes",
  "node_selector": { "drone": true },
  "platform": { "arch": "amd64", "os": "linux" },
  "steps":
    [
      {
        "environment": { "DOCKER_BUILDKIT": 1 },
        "image": "plugins/docker",
        "name": "Build container image",
        "pull": "always",
        "settings": { "dry_run": true, "purge": true, "repo": "build-only" },
        "trigger": { "event": ["pull_request"] },
        "when": { "branch": { "exclude": ["master"] } },
      },
      {
        "environment": { "DOCKER_BUILDKIT": 1 },
        "image": "plugins/docker",
        "name": "Publish image kradalby/gso",
        "pull": "always",
        "settings":
          {
            "password": { "from_secret": "docker_password" },
            "purge": true,
            "repo": "kradalby/gso",
            "tags":
              [
                "latest",
                "latest-${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}",
                "${DRONE_COMMIT_SHA:0:8}",
              ],
            "username": { "from_secret": "docker_username" },
          },
        "when": { "branch": ["master", "main"], "event": ["push"] },
      },
      {
        "commands":
          [
            "kubectl -n $APP set image deployment/$APP $APP=$REPO:${DRONE_COMMIT_SHA:0:8} --record",
            "kubectl -n $APP rollout status deployment $APP",
          ],
        "environment":
          {
            "APP": "gso",
            "KUBERNETES_CERT": { "from_secret": "kubernetes_cert" },
            "KUBERNETES_SERVER": { "from_secret": "kubernetes_server" },
            "KUBERNETES_TOKEN": { "from_secret": "kubernetes_token" },
            "REPO": "kradalby/gso",
          },
        "image": "kradalby/drone-kubectl",
        "name": "Deploy gso to Kubernetes",
        "pull": "always",
        "when": { "branch": ["master", "main"], "event": ["push"] },
      },
    ],
  "type": "kubernetes",
}
