image: kradalby/ci-tox
git:
  path: github.com/kradalby/gso

script:
    - tox

notify:
  email:
    recipients:
      - kradalby@kradalby.no


deploy:
  bash:
    script:
        - 'git clone https://github.com/kradalby/plays.git'
        - 'ansible-playbook -i plays/inventory plays/deploy/gso.yml'
